import './bootstrap';
// import './plugins/jquery/jquery.min.js';
// import './plugins/bootstrap/js/bootstrap.bundle.min.js';
// // import './plugins/datatables/jquery.dataTables.min.js';
// import './plugins/datatables-bs4/js/dataTables.bootstrap4.min.js';
// import './plugins/datatables-responsive/js/dataTables.responsive.min.js';
// import './plugins/datatables-responsive/js/responsive.bootstrap4.min.js';
// import './plugins/datatables-buttons/js/dataTables.buttons.min.js';
// import './plugins/jszip/jszip.min.js';
// import './plugins/pdfmake/pdfmake.min.js';
// import './plugins/pdfmake/vfs_fonts.js';
// import './plugins/datatables-buttons/js/buttons.html5.min.js';
// import './plugins/datatables-buttons/js/buttons.print.min.js';
// import './plugins/datatables-buttons/js/buttons.colVis.min.js';
import './dist/js/adminlte.min.js?v=3.2.0';
import './dist/js/demo.js';
